language: python

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache: pip

python:
    - '3.7'

before_install:
    - pip install poetry

install:
    - poetry install

script: poetry run pytest
