branches:
  only:
  - master

language: python

cache: pip

python:
    - '3.7'

before_install:
    - pip install poetry
    - pip install codecov

install:
    - poetry install

script: poetry run pytest

after_script: coverage run tests.py

after_success:
    - codecov
